name: ZAP Security Scan

on:
  push:
    branches: [ main ]
  pull_request: {}

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug: Show workspace contents
        run: ls -la

      - name: Set up Docker
        run: |
          docker network create zap-net
          docker pull bkimminich/juice-shop
          docker pull owasp/zap2docker-stable
          
          # Debug: Show Docker images and network
          docker images
          docker network inspect zap-net

      - name: Start Juice Shop
        run: |
          docker run -d \
            --network zap-net \
            --name juice-shop \
            -p 3000:3000 \
            bkimminich/juice-shop
          sleep 30
          
          # Debug: Verify Juice Shop is running
          docker ps
          curl -v http://localhost:3000 || true

      - name: Prepare reports directory
        run: |
          mkdir -p zap-reports
          chmod 777 zap-reports
          # Debug: Verify directory permissions
          ls -ld zap-reports
          touch zap-reports/testfile && echo "Directory writable" || echo "Directory not writable"

      - name: Run ZAP Scan
        run: |
          docker run \
            --network zap-net \
            -v $(pwd)/zap-reports:/zap/wrk/:rw \
            -e ZAP_USER=root \
            -t owasp/zap2docker-stable \
            zap-baseline.py \
            -t http://juice-shop:3000 \
            -r /zap/wrk/zap_report.html \
            -J /zap/wrk/zap_report.json \
            -x /zap/wrk/report.xml \
            -a
          
          # Debug: Show container logs
          docker logs $(docker ps -lq) || true

      - name: Verify reports
        run: |
          # Debug: Check report files
          ls -la zap-reports/
          test -f zap-reports/zap_report.html && echo "HTML report exists" || echo "HTML report missing"
          test -f zap-reports/zap_report.json && echo "JSON report exists" || echo "JSON report missing"
          test -f zap-reports/report.xml && echo "XML report exists" || echo "XML report missing"

      - name: Upload Reports
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: zap-reports/*

      - name: Cleanup
        if: always()
        run: |
          # Debug: Show containers before cleanup
          docker ps -a
          
          docker rm -f juice-shop || true
          docker network rm zap-net || true
          
          # Debug: Verify cleanup
          docker ps -a
          docker network ls
