name: ZAP Security Scan

on:
  push:
    branches: [ main ]
  pull_request: {}

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zaproxy/zap-stable:latest
      options: --network host

    steps:
      - name: Start Juice Shop
        run: |
          docker run -d \
            -p 3000:3000 \
            --name juice-shop \
            bkimminich/juice-shop
          sleep 30  # Increased wait time

      - name: Run ZAP Baseline Scan
        run: |
          zap-baseline.py \
            -t http://localhost:3000 \
            -r zap_report.html \
            -J zap_report.json \
            -x report.xml \
            -a

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: |
            zap_report.html
            zap_report.json
            report.xml

      - name: Cleanup
        if: always()
        run: docker rm -f juice-shop || true
