name: ZAP Security Scan

on:
  push:
    branches: [ main ]
  pull_request: {}

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          docker network create zap-net
          docker pull bkimminich/juice-shop
          docker pull owasp/zap2docker-stable

      - name: Start Juice Shop
        run: |
          docker run -d \
            --network zap-net \
            --name juice-shop \
            -p 3000:3000 \
            bkimminich/juice-shop
          sleep 30

      - name: Prepare reports directory
        run: |
          mkdir -p zap-reports
          chmod 777 zap-reports

      - name: Run ZAP Scan
        run: |
          docker run \
            --network zap-net \
            -v $(pwd)/zap-reports:/zap/wrk/:rw \
            -e ZAP_USER=root \
            -t owasp/zap2docker-stable \
            zap-baseline.py \
            -t http://juice-shop:3000 \
            -r /zap/wrk/zap_report.html \
            -J /zap/wrk/zap_report.json \
            -x /zap/wrk/report.xml \
            -a

      - name: Check if reports exist
        run: |
          ls -la zap-reports/
          test -f zap-reports/zap_report.html || echo "Report file missing"

      - name: Upload Reports
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: zap-reports/*

      - name: Cleanup
        if: always()
        run: |
          docker rm -f juice-shop || true
          docker network rm zap-net || true
