name: ZAP Scan

on:
  push:
    branches:
      - main
  pull_request: {}  # Optional: Add this to run on PRs too

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Start Juice Shop (target app)
        run: |
          docker pull bkimminich/juice-shop
          docker run -d -p 3000:3000 --name juice-shop bkimminich/juice-shop
          sleep 20 # Wait for app to start

      - name: Run OWASP ZAP scan
        run: |
          docker run --network host -v ${{ github.workspace }}:/zap/wrk:rw \
          ghcr.io/zaproxy/zap-stable:latest zap-baseline.py \
          -t http://localhost:3000 \
          -r zap_report.html
          
      - name: Save ZAP report to repo
        run: |
          mkdir -p zap-output
          mv zap_report.* report.xml zap-output/
          git config --global user.email "akashsonawane571@gmail.com"
          git config --global user.name "Akashsonawane571"
          git checkout -b zap-report
          cp -r zap-output/* .
          git add .
          git commit -m "Add ZAP scan report"
          git push origin zap-report --force

      - name: Cleanup
        if: always()  # Run even if previous steps fail
        run: |
          docker stop juice-shop || true
          docker rm juice-shop || true
